---
name: Test-Fork
version: 0.01_01
author:
  - 'Michael G Schwern E<lt>schwern@pobox.comE<gt>'
abstract: test code which forks
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::Builder::Module: 0.02
  Test::More: 0.62
provides:
  Test::Fork:
    file: lib/Test/Fork.pm
    version: 0.01_01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
